steps:
  # 1. Construir la imagen Docker genérica
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/fudo-etl-repo/fudo-gen-image:latest', '.']
    id: 'Build'

  # 2. Subir la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/fudo-etl-repo/fudo-gen-image:latest']
    id: 'Push'

  # 3. Desplegar/Actualizar Job de d-002-miguitas
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'd-002-miguitas'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/fudo-etl-repo/fudo-gen-image:latest'
      - '--set-env-vars=CLIENT_NAME=miguitas,GCP_PROJECT_ID=$PROJECT_ID,FUDO_AUTH_ENDPOINT=https://auth.fu.do/api,FUDO_API_BASE_URL=https://api.fu.do'
      - '--set-secrets=DB_CONNECTION_STRING=D-002-MIGUITAS-DB-CONN:latest'
      - '--region=southamerica-east1'
      - '--task-timeout=7200'  
      - '--memory=2Gi'         
      - '--cpu=1'
    id: 'Deploy-Miguitas'

  # 4. Desplegar/Actualizar Job de d-003-amoremio
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'd-003-amoremio'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/fudo-etl-repo/fudo-gen-image:latest'
      - '--set-env-vars=CLIENT_NAME=amoremio,GCP_PROJECT_ID=$PROJECT_ID,FUDO_AUTH_ENDPOINT=https://auth.fu.do/api,FUDO_API_BASE_URL=https://api.fu.do'
      - '--set-secrets=DB_CONNECTION_STRING=D-003-AMOREMIO-DB-CONN:latest'
      - '--region=southamerica-east1'
      - '--task-timeout=7200'  
      - '--memory=2Gi'         
      - '--cpu=1'
    id: 'Deploy-Amoremio'

    # 5. Desplegar/Actualizar Job de d-004-bodegon
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'd-004-bodegon'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/fudo-etl-repo/fudo-gen-image:latest'
      # Ajustamos CLIENT_NAME a bodegon
      - '--set-env-vars=CLIENT_NAME=bodegon,GCP_PROJECT_ID=$PROJECT_ID,FUDO_AUTH_ENDPOINT=https://auth.fu.do/api,FUDO_API_BASE_URL=https://api.fu.do'
      # El nombre del secreto debe ser el que creaste en GCP
      - '--set-secrets=DB_CONNECTION_STRING=D-003-BODEGON-DB-CONN:latest'
      - '--region=southamerica-east1'
      - '--task-timeout=7200'  
      - '--memory=2Gi'         
      - '--cpu=1'
    id: 'Deploy-Bodegon'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/fudo-etl-repo/fudo-gen-image:latest'

options:
  logging: CLOUD_LOGGING_ONLY