-- fudo_etl/sql/initial_grants.sql
GRANT USAGE ON SCHEMA public TO sudata_owner;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO sudata_owner;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO sudata_owner;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO sudata_owner;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sudata_owner;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sudata_owner;